/**
 * Coverage ratchet — the anti-narrowing floor for the Oracle closure gate.
 *
 * The closure gate (coverage-union.test.js) proves the *current* union is
 * green.  That alone does not stop the contract from being quietly *narrowed*
 * to make green cheaper — the meta-version of the hollow-test failure mode:
 *
 *   - drop a scenario and the branch it lit, then remove that branch from the
 *     in-contract set → gate still "green", coverage silently lost;
 *   - add a bogus entry to the one-way register to reclassify a should-be-
 *     both-ways branch as "correctly dead" → gate still "green", gap hidden.
 *
 * The ratchet freezes the contract in a committed baseline and fails if it
 * erodes.  What it can enforce mechanically:
 *
 *   - the set of in-contract decision sites must not SHRINK (branches can be
 *     added — the gate holds new ones to the same both-ways bar — but not
 *     silently removed);
 *   - the one-way / correctly-dead registers must match the baseline EXACTLY;
 *   - the dispatch multiway must still realize every baseline arm;
 *   - the union must still execute (distinct-PC floor — un-fakeable by static
 *     assertions).
 *
 * What it deliberately does NOT pretend to do: mechanically prove a one-way
 * claim is *legitimate*.  "Correctly dead" vs. "we didn't try hard enough" is
 * not decidable from a trace (ADR-0007 makes it a human, source-grounded
 * judgement).  So the ratchet's job is to make every such claim a VISIBLE,
 * REVIEWABLE diff to coverage-baseline.json — never a silent code edit.  The
 * exact-match on the registers is precisely that tripwire.
 */

import { DISPATCH_ADDR } from './coverage-union.js';

const oct = (n) => n.toString(8);

/** Realized arms of the outline-compiler dispatch (00443) — a fixed contract.
 *  Other `jmp .` sites are self-modifying returns whose targets vary by
 *  scenario mix, so they are not ratcheted (the gate's no-dark check covers
 *  them). */
function dispatchArms(result) {
  const d = result.multiwayEntries.find((e) => e.addr === DISPATCH_ADDR);
  return d ? [...d.realizedTargets].sort((a, b) => a - b).map(oct) : [];
}

/**
 * Build the committed baseline object from a passing runUnionClosure() result.
 * Derived from truth (never hand-typed) so it cannot reintroduce the copy
 * errors — inverted directions, wrong addresses — the audit found.
 */
export function buildBaseline({ result, listing, allPcs }) {
  const register = new Map();
  for (const e of result.oneWayConfirmed) register.set(oct(e.addr), e.direction);

  return {
    _comment:
      'Coverage ratchet floor for the Spacewar 3.1 Oracle (ADR-0007/0012). ' +
      'Generated by gen-coverage-baseline.mjs from a passing union closure. ' +
      'Any diff here is a deliberate change to the coverage contract and MUST ' +
      'be reviewed: shrinking a set or editing a register is how a real gap ' +
      'gets hidden. Regenerate only after confirming the union is genuinely green.',
    inContractSkipSites: [...listing.skipSites.keys()].sort((a, b) => a - b).map(oct),
    inContractMultiwaySites: [...listing.multiwayBranches.keys()].sort((a, b) => a - b).map(oct),
    oneWayRegister: Object.fromEntries(
      [...register.entries()].sort((a, b) => parseInt(a[0], 8) - parseInt(b[0], 8)),
    ),
    deadMultiway: result.deadMultiwayConfirmed.map((e) => oct(e.addr)).sort(),
    deadSkipSites: result.deadSkipConfirmed.map((e) => oct(e.addr)).sort(),
    dispatchArms: dispatchArms(result),
    // Execution-proof floor: the union must observe at least this many distinct
    // PCs. A static / hollow reimplementation produces ~0. Set a bit below the
    // observed count so incidental drift does not false-alarm.
    minDistinctPcs: Math.floor(allPcs.size * 0.95),
  };
}

/**
 * Compare a fresh runUnionClosure() result against the committed baseline.
 * Returns { ok, violations: string[] } — ok iff nothing eroded.
 */
export function checkRatchet(baseline, { result, listing, allPcs }) {
  const violations = [];

  // 1. In-contract decision sites must not shrink.
  const curSkip = new Set([...listing.skipSites.keys()].map(oct));
  for (const addr of baseline.inContractSkipSites) {
    if (!curSkip.has(addr)) {
      violations.push(
        `in-contract skip site ${addr} disappeared — the coverage contract was narrowed`);
    }
  }
  const curMulti = new Set([...listing.multiwayBranches.keys()].map(oct));
  for (const addr of baseline.inContractMultiwaySites) {
    if (!curMulti.has(addr)) {
      violations.push(
        `in-contract multiway site ${addr} disappeared — the coverage contract was narrowed`);
    }
  }

  // 2. One-way / correctly-dead registers must match EXACTLY (any change is a
  //    reviewable baseline diff, never a silent code edit).
  const curOneWay = new Map(result.oneWayConfirmed.map((e) => [oct(e.addr), e.direction]));
  const baseOneWay = new Map(Object.entries(baseline.oneWayRegister));
  for (const [addr, dir] of baseOneWay) {
    if (!curOneWay.has(addr)) {
      violations.push(`one-way ${addr} (${dir}) no longer confirmed one-way in the union`);
    } else if (curOneWay.get(addr) !== dir) {
      violations.push(
        `one-way ${addr} direction changed ${dir} → ${curOneWay.get(addr)} without a baseline update`);
    }
  }
  for (const addr of curOneWay.keys()) {
    if (!baseOneWay.has(addr)) {
      violations.push(
        `one-way ${addr} added without a baseline update — a new "correctly dead" claim must be reviewed`);
    }
  }

  const setEq = (label, cur, base) => {
    const c = new Set(cur), b = new Set(base);
    for (const x of b) if (!c.has(x)) violations.push(`${label} ${x} dropped vs baseline`);
    for (const x of c) if (!b.has(x)) violations.push(`${label} ${x} added without a baseline update`);
  };
  setEq('dead-multiway', result.deadMultiwayConfirmed.map((e) => oct(e.addr)), baseline.deadMultiway);
  setEq('dead-skip-site', result.deadSkipConfirmed.map((e) => oct(e.addr)), baseline.deadSkipSites);

  // 3. Dispatch multiway must still realize every baseline arm.
  const curArms = new Set(dispatchArms(result));
  for (const arm of baseline.dispatchArms) {
    if (!curArms.has(arm)) violations.push(`dispatch arm ${arm} no longer realized`);
  }

  // 4. Execution-proof floor.
  if (allPcs.size < baseline.minDistinctPcs) {
    violations.push(
      `distinct PCs ${allPcs.size} < floor ${baseline.minDistinctPcs} — the union barely executed; ` +
      `is the run static/stubbed?`);
  }

  return { ok: violations.length === 0, violations };
}
